a = input("Digite algo: ")
print(f"Qual é o tipo dele? {type(a)}")
print(f"É apenas espaço? {a.isspace()}")
print(f"É númerico? {a.isnumeric()}")
print(f"É alfabetico? {a.isalpha()}")
print(f"É alnumerico? {a.isalnum()}")
print(f"Esta em maisculo? {a.isupper()}")
print(f"Esta em minusculo? {a.islower()}")
print(f"Esta capitalizada? {a.istitle()}")
